# Generated by Django 5.0 on 2023-12-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shestory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='end_of_reign',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='start_of_reign',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='civilizationreference',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countryreference',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rolereference',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
